package msg

// en は英語のカタログ。ロケールが ja 以外、または未設定のときに選ばれる。
var en = Catalog{
	State: StateMsg{
		CannotRead:  "cannot read %s: %w",
		Corrupt:     "%s is corrupt (delete it and the next apply will recreate it): %w",
		NewerFormat: "%s uses a newer format (version %d > %d); update llmtpl",
	},
	JSON: JSONMsg{
		NotJSON:       "%s: not valid JSON: %w",
		NotObject:     "%s: the top level must be an object ({...})",
		FormatFailed:  "cannot format JSON: %w",
		TypeMismatch:  "%s: type mismatch for key %q (existing: %s / fragment: %s)",
		CannotCompare: "cannot compare array elements: %w",
		TypeObject:    "object",
		TypeArray:     "array",
		TypeScalar:    "scalar",
	},
	Render: RenderMsg{
		NoTmplPath:          "TmplPath is required",
		EmptySlotName:       "slot name is empty",
		PartialsGlobFailed:  "cannot scan partials: %w",
		PartialsParseFailed: "cannot parse partials: %w",
		SourceParseFailed:   "cannot parse %s: %w",
		TemplateParseFailed: "cannot parse template: %w",
		ExecFailed:          "cannot evaluate template (possibly a reference to an undefined flag): %w",
	},
	FileOut: FileOutMsg{
		ArchiveFailed:          "cannot archive the existing file: %w",
		MkdirParentFailed:      "%s: cannot create the parent directory: %w",
		TempCreateFailed:       "%s: cannot create a temporary file: %w",
		TempWriteFailed:        "%s: cannot write the temporary file: %w",
		TempCloseFailed:        "%s: cannot close the temporary file: %w",
		ChmodFailed:            "%s: cannot set permissions: %w",
		ReplaceFailed:          "%s: cannot replace the file: %w",
		NoArchiveDir:           "%s: found a file that llmtpl did not generate, but no archive directory (ArchiveDir) is set",
		ArchiveDirCreateFailed: "cannot create the archive directory: %w",
		ArchiveNamesExhausted:  "no free name left in the archive directory: %s/%s",
	},
	Link: LinkMsg{
		CannotUnlink:       "cannot remove %s: %w",
		WouldArchive:       "(dry-run) needs archiving",
		CannotLink:         "cannot create link %s: %w",
		CannotArchive:      "cannot archive %s: %w",
		CannotRead:         "cannot read %s: %w",
		ConflictNote:       "%s: %s skipped because %s provides it first",
		LayerOutsideOutDir: "a scanned layer points outside outDir: %s",
	},
	Flags: FlagsMsg{
		Section:           "%s:%d: sections are not allowed (a conf is a flat list of `key = value`; per-target overrides belong in that target's conf): %s",
		NoEquals:          "%s:%d: missing `=`: %s",
		EmptyKey:          "%s:%d: the key is empty: %s",
		BoolOnly:          "%s:%d: the value must be true or false: %s = %s",
		ReadFailed:        "%s: cannot read the file: %w",
		EmptyValue:        "%s:%d: %s has an empty value (write the path to the bundle root)",
		PathKeyNotBool:    "%s:%d: %s takes a path, not true/false: %s = %s",
		TildeExpandFailed: "%s:%d: cannot expand ~ in %s: %w",
		TildeUserForm:     "%s:%d: %s does not support the ~username form (use an absolute path, or a path relative to this conf): %s",
		NoBundles:         "(no bundles)",
		UnknownFlag:       "%s: unknown flag: %s (no bundle directory has that name). Available: %s",
	},
	Bundle: BundleMsg{
		CannotRead:      "cannot read %s: %w",
		CannotReadRoot:  "cannot read the bundle root: %w",
		LayoutViolation: "bundle %s: %s/ cannot sit directly in the bundle (move it under a dot-prefixed layer, e.g. %s/%s/)",
		UnknownMetaKey:  "%s: line %d: unknown key: %s (only description is allowed)",
		NoColon:         "line %d: missing `:`: %s",
		EmptyKey:        "line %d: the key is empty: %s",
	},
}
