package msg

// en は英語のカタログ。ロケールが ja 以外、または未設定のときに選ばれる。
var en = Catalog{
	State: StateMsg{
		CannotRead:  "cannot read %s: %w",
		Corrupt:     "%s is corrupt (delete it and the next apply will recreate it): %w",
		NewerFormat: "%s uses a newer format (version %d > %d); update llmtpl",
	},
	JSON: JSONMsg{
		NotJSON:       "%s: not valid JSON: %w",
		NotObject:     "%s: the top level must be an object ({...})",
		FormatFailed:  "cannot format JSON: %w",
		TypeMismatch:  "%s: type mismatch for key %q (existing: %s / fragment: %s)",
		CannotCompare: "cannot compare array elements: %w",
		TypeObject:    "object",
		TypeArray:     "array",
		TypeScalar:    "scalar",
	},
	Render: RenderMsg{
		NoTmplPath:          "TmplPath is required",
		EmptySlotName:       "slot name is empty",
		PartialsGlobFailed:  "cannot scan partials: %w",
		PartialsParseFailed: "cannot parse partials: %w",
		SourceParseFailed:   "cannot parse %s: %w",
		TemplateParseFailed: "cannot parse template: %w",
		ExecFailed:          "cannot evaluate template (possibly a reference to an undefined flag): %w",
	},
	FileOut: FileOutMsg{
		ArchiveFailed:          "cannot archive the existing file: %w",
		MkdirParentFailed:      "%s: cannot create the parent directory: %w",
		TempCreateFailed:       "%s: cannot create a temporary file: %w",
		TempWriteFailed:        "%s: cannot write the temporary file: %w",
		TempCloseFailed:        "%s: cannot close the temporary file: %w",
		ChmodFailed:            "%s: cannot set permissions: %w",
		ReplaceFailed:          "%s: cannot replace the file: %w",
		NoArchiveDir:           "%s: found a file that llmtpl did not generate, but no archive directory (ArchiveDir) is set",
		ArchiveDirCreateFailed: "cannot create the archive directory: %w",
		ArchiveNamesExhausted:  "no free name left in the archive directory: %s/%s",
	},
	Link: LinkMsg{
		CannotUnlink:       "cannot remove %s: %w",
		WouldArchive:       "(dry-run) needs archiving",
		CannotLink:         "cannot create link %s: %w",
		CannotArchive:      "cannot archive %s: %w",
		CannotRead:         "cannot read %s: %w",
		ConflictNote:       "%s: %s skipped because %s provides it first",
		LayerOutsideOutDir: "a scanned layer points outside outDir: %s",
	},
	Flags: FlagsMsg{
		Section:           "%s:%d: sections are not allowed (a conf is a flat list of `key = value`; per-target overrides belong in that target's conf): %s",
		NoEquals:          "%s:%d: missing `=`: %s",
		EmptyKey:          "%s:%d: the key is empty: %s",
		BoolOnly:          "%s:%d: the value must be true or false: %s = %s",
		ReadFailed:        "%s: cannot read the file: %w",
		EmptyValue:        "%s:%d: %s has an empty value (write the path to the bundle root)",
		PathKeyNotBool:    "%s:%d: %s takes a path, not true/false: %s = %s",
		TildeExpandFailed: "%s:%d: cannot expand ~ in %s: %w",
		TildeUserForm:     "%s:%d: %s does not support the ~username form (use an absolute path, or a path relative to this conf): %s",
		NoBundles:         "(no bundles)",
		UnknownFlag:       "%s: unknown flag: %s (no bundle directory has that name). Available: %s",
	},
	Bundle: BundleMsg{
		CannotRead:      "cannot read %s: %w",
		CannotReadRoot:  "cannot read the bundle root: %w",
		LayoutViolation: "bundle %s: %s/ cannot sit directly in the bundle (move it under a dot-prefixed layer, e.g. %s/%s/)",
		UnknownMetaKey:  "%s: line %d: unknown key: %s (only description is allowed)",
		NoColon:         "line %d: missing `:`: %s",
		EmptyKey:        "line %d: the key is empty: %s",
	},
	Apply: ApplyMsg{
		ReservedBundleName:     "%s: a bundle cannot be named after a reserved key (you could no longer turn on a flag of that name in a conf). Rename the directory.",
		BundleRootInDefaults:   "%s:%d: %s cannot be written in %s (this file lives inside the bundle root, so the root is already resolved by the time it is read). Use --tpl-home, the %s environment variable, or the target's %s.",
		UnknownSlot:            "%s: no bundle matches slot %q (typo? available: %s)",
		TargetUnderRoot:        "%s is inside the bundle root (%s); bundle fragments cannot be targets",
		NotReadAtThisPath:      "%s is never read (the target is the project root). Move it to %s.",
		IsOverlayLayer:         "%s is not a target but an overlay layer of %s. Run from the parent directory.",
		NotGeneratedUnderLayer: "%s is not generated under %s/ (Claude Code does not read that location; put %s directly in the target): %s",
		SkippedUnsupported:     "unsupported type (.md and .json only)",
		TmplScanFailed:         "cannot scan templates: %w",
		HomeOrder:              "--tpl-home → the %[1]s environment variable → %[3]s in %[2]s → %[4]s/ found by walking up → ~/.config/llmtpl",
		HomeLabelEnv:           "the %s environment variable",
		HomeLabelConf:          "%[2]s in %[1]s",
		HomeLabelWalkUp:        "found by walking up",
		ExplicitHomeMissing:    "the specified bundle root does not exist: %s",
		EnvHomeMissing:         "the bundle root that %s points to does not exist: %s",
		ConfHomeMissing:        "%s: the bundle root that %s points to does not exist: %s",
		HomeNotFound:           "no bundle root found. Specify one of: %s",
		TargetScanFailed:       "cannot scan for targets: %w",
	},
	Cmd: CmdMsg{
		Short: "A template engine for AI agent config",
		Long: `llmtpl — composes AI agent config (CLAUDE.md and .claude/) from per-flag bundles.

Bundle root resolution order: %s`,
		StaleGenerated: "the generated files are out of date (%d differences). Run llmtpl apply.",
		FlagTplHome:    "bundle root (see --help for the resolution order when omitted)",
		FlagDryRun:     "show the differences without writing",
		FlagVerbose:    "also show fragments that were not inserted and links that already exist",
		ApplyShort:     "generate and compose (defaults to cwd)",
		CheckShort:     "check whether the generated files are up to date (exit 2 on differences)",
		StatusShort:    "show the effective value of every flag per target",
		BundlesShort:   "list the bundles",
		DroppedTargets: "excluded %d directories under the bundle root from the targets\n",
		NoTargets:      "no target found: %s (searched recursively, 0 found; a target is a directory with %s or *.tmpl)",
		TargetCount:    "%d targets\n",
		BundleRootLine: "bundle root: %s (%s)\n",
		OnNone:         "(none)",
		Skip:           "  ⏭ skipped %s — %s\n",
		Diff:           "  ~ differs %s\n",
		Generated:      "  ✅ generated %s\n",
		Unchanged:      "  = unchanged %s\n",
		ArchivedEntity: "     ⚠️  archived a file llmtpl did not generate: %s\n",
		ArchivedHint:   "        if you had edited it by hand, fold the differences back into the template.\n",
		WouldArchive:   "     ⚠️  a file llmtpl did not generate is present (apply would archive it)\n",
		Orphan:         "  ⚠️  %[2]s from %[1]s did not land (this target has no %[3]s; create it and it will)\n",
		LinkPlanned:    "  ~ will link %s -> %s\n",
		Linked:         "  🔗 linked %s -> %s\n",
		UnlinkPlanned:  "  ~ will unlink %s\n",
		Unlinked:       "  ✂️  unlinked %s\n",
		LinkArchived:   "     ⚠️  archived a file found at the link path: %s\n",
		LinkConflict:   "     ⚠️  name conflict: %s\n",
		LinkKept:       "     = already linked %s\n",
		NoBundles:      "(no bundles)",
		ColTarget:      "target",
		ColBundle:      "bundle",
		ColContents:    "contents",
		ColDesc:        "description",
	},
	ConfEdit: ConfEditMsg{
		LineVanished: "%s: cannot find the line to rewrite (the conf may have changed after it was read)",
	},
	Interactive: InteractiveMsg{
		NoConfHere:     "%s has no %s anywhere below it.\n",
		CreateConfirm:  "Create %s and continue? (this directory becomes a target)",
		CreateDeclined: "Aborted (did not create %s).\n",
		SelectTitle:    "Flags to enable (space toggle / enter submit / esc abort)",
		DefaultOnNote:  "[default ON]",
		Changes:        "\nChanges:\n",
		TargetHeader:   "  ▸ %s\n",
		ChangeReplace:  "  ~ %s: %s → %s\n",
		ChangeAppend:   "  + %s = %s (appended)\n",
		NoChanges:      "\nNo flag changes (%s will not be modified).\n",
		NoChangesNew:   "\nNo flag changes (%s will be created with the defaults).\n",
		ConfirmTitle:   "Update %s and run apply?",
		Affirmative:    "Yes",
		Negative:       "No",
		WroteConf:      "  ✏️  updated %s\n",
		CreatedConf:    "  ✏️  created %s\n",
		Canceled:       "Canceled (nothing was changed).",
	},
}
