package msg

// ja は日本語のカタログ。ロケールが ja で始まるときに選ばれる。
var ja = Catalog{
	State: StateMsg{
		CannotRead:  "%s を読めません: %w",
		Corrupt:     "%s が壊れています（削除すれば次回 apply で作り直します）: %w",
		NewerFormat: "%s は新しい形式です（version %d > %d）。llmtpl を更新してください",
	},
	JSON: JSONMsg{
		NotJSON:       "%s: JSON として読めません: %w",
		NotObject:     "%s: トップレベルはオブジェクト（{...}）である必要があります",
		FormatFailed:  "JSON の整形に失敗: %w",
		TypeMismatch:  "%s: キー %q の型が一致しません（既存: %s / 断片: %s）",
		CannotCompare: "配列要素を比較できません: %w",
		TypeObject:    "オブジェクト",
		TypeArray:     "配列",
		TypeScalar:    "値",
	},
	Render: RenderMsg{
		NoTmplPath:          "TmplPath が未指定です",
		EmptySlotName:       "slot 名が空です",
		PartialsGlobFailed:  "partials の探索に失敗: %w",
		PartialsParseFailed: "partials のパースに失敗: %w",
		SourceParseFailed:   "%s のパースに失敗: %w",
		TemplateParseFailed: "テンプレートのパースに失敗: %w",
		ExecFailed:          "テンプレートの評価に失敗（未定義フラグ参照の可能性）: %w",
	},
	FileOut: FileOutMsg{
		ArchiveFailed:          "退避に失敗: %w",
		MkdirParentFailed:      "%s: 親ディレクトリを作れません: %w",
		TempCreateFailed:       "%s: 一時ファイルを作れません: %w",
		TempWriteFailed:        "%s: 一時ファイルを書けません: %w",
		TempCloseFailed:        "%s: 一時ファイルを閉じられません: %w",
		ChmodFailed:            "%s: 権限を設定できません: %w",
		ReplaceFailed:          "%s: 置き換えに失敗: %w",
		NoArchiveDir:           "%s: 生成物でない実体があるのに退避先（ArchiveDir）が未設定です",
		ArchiveDirCreateFailed: "退避先を作れません: %w",
		ArchiveNamesExhausted:  "退避先の名前が埋まっています: %s/%s",
	},
	Link: LinkMsg{
		CannotUnlink:       "%s を外せません: %w",
		WouldArchive:       "(dry-run) 退避が必要",
		CannotLink:         "%s を張れません: %w",
		CannotArchive:      "%s を退避できません: %w",
		CannotRead:         "%s を読めません: %w",
		ConflictNote:       "%s の %s は %s が先に提供しているためスキップ",
		LayerOutsideOutDir: "走査層が outDir の外を指しています: %s",
	},
	Flags: FlagsMsg{
		Section:           "%s:%d: セクションは書けません（conf は平坦な `key = value` のみ。フラグの上書きはターゲットごとの conf に書く）: %s",
		NoEquals:          "%s:%d: = がありません: %s",
		EmptyKey:          "%s:%d: キー名が空です: %s",
		BoolOnly:          "%s:%d: 値は true / false のみ: %s = %s",
		ReadFailed:        "%s: 読み込みに失敗: %w",
		EmptyValue:        "%s:%d: %s の値が空です（バンドルルートのパスを書きます）",
		PathKeyNotBool:    "%s:%d: %s はパスを書くキーです（true / false ではありません）: %s = %s",
		TildeExpandFailed: "%s:%d: %s の ~ を展開できません: %w",
		TildeUserForm:     "%s:%d: %s の ~ユーザー名 形式は使えません（絶対パスか、この conf からの相対パスで書きます）: %s",
		NoBundles:         "（バンドルがありません）",
		UnknownFlag:       "%s: 未知のフラグ: %s（同名のバンドルディレクトリがありません）。利用可能: %s",
	},
	Bundle: BundleMsg{
		CannotRead:      "%s を読めません: %w",
		CannotReadRoot:  "バンドルルートを読めません: %w",
		LayoutViolation: "バンドル %s: %s/ はバンドル直下に置けません（%s/%s/ のようにドット始まりの層へ移してください）",
		UnknownMetaKey:  "%s: %d 行目: 未知のキー: %s（使えるのは description）",
		NoColon:         "%d 行目: : がありません: %s",
		EmptyKey:        "%d 行目: キー名が空です: %s",
	},
	Apply: ApplyMsg{
		ReservedBundleName:     "%s: バンドル名に予約キーは使えません（conf で同名のフラグを ON にできなくなるため）。ディレクトリ名を変えてください",
		BundleRootInDefaults:   "%s:%d: %s は %s には書けません（このファイル自体がバンドルルートの中にあるため、読む時点でルートは解決済み）。--tpl-home / 環境変数 %s / ターゲットの %s のいずれかを使ってください",
		UnknownSlot:            "%s: slot %q に対応するバンドルがありません（タイポ？ 有効: %s）",
		TargetUnderRoot:        "%s はバンドルルート（%s）の配下です。バンドルの断片はターゲットにできません",
		NotReadAtThisPath:      "%s は読まれません（ターゲットはプロジェクトルートです）。%s へ移してください",
		IsOverlayLayer:         "%s はターゲットではなく %s のオーバーレイ層です。親ディレクトリで実行してください",
		NotGeneratedUnderLayer: "%s は %s/ 配下では生成対象外です（Claude Code が読まない位置のため。%s はターゲット直下へ置いてください）: %s",
		SkippedUnsupported:     "未対応の種類（.md / .json のみ）",
		TmplScanFailed:         "テンプレの探索に失敗: %w",
		HomeOrder:              "--tpl-home → 環境変数 %s → %s の %s → 親を辿って %s/ → ~/.config/llmtpl",
		ConfHomeConflict:       "%s の指定が食い違っています（同じ実行で 1 つに定まりません）:\n  %s → %s\n  %s → %s",
		HomeLabelEnv:           "環境変数 %s",
		HomeLabelConf:          "%s の %s",
		HomeLabelWalkUp:        "親探索",
		ExplicitHomeMissing:    "指定されたバンドルルートがありません: %s",
		EnvHomeMissing:         "%s が指すバンドルルートがありません: %s",
		ConfHomeMissing:        "%s: %s が指すバンドルルートがありません: %s",
		HomeNotFound:           "バンドルルートが見つかりません。次のいずれかで指定してください: %s",
		TargetScanFailed:       "ターゲットの探索に失敗: %w",
	},
	Cmd: CmdMsg{
		Short: "LLM 設定のテンプレートエンジン",
		Long: `llmtpl — LLM 設定（CLAUDE.md / .claude 配下）をフラグ単位のバンドルから合成する。

バンドルルートの解決順: %s`,
		StaleGenerated: "生成物が最新ではありません（%d 件の差分）。llmtpl apply を実行してください",
		FlagTplHome:    "バンドルルート（省略時の解決順は --help の説明を参照）",
		FlagDryRun:     "書き込まず差分だけ表示する",
		FlagVerbose:    "差し込まれなかった寄稿・既存リンクも表示する",
		ApplyShort:     "生成 + 合成（既定は cwd）",
		CheckShort:     "生成物が最新かを検査する（差分ありで exit 2）",
		StatusShort:    "ターゲット × フラグの実効値を表示する",
		BundlesShort:   "バンドル一覧を表示する",
		DroppedTargets: "バンドルルート配下の %d 件をターゲットから除外しました\n",
		NoTargets:      "ターゲットが見つかりません: %s（配下まで探索して 0 件。%s か *.tmpl を持つディレクトリが対象）",
		TargetCount:    "対象 %d 件\n",
		BundleRootLine: "バンドルルート: %s（%s）\n",
		OnNone:         "（なし）",
		Skip:           "  ⏭ スキップ %s — %s\n",
		Diff:           "  ~ 差分あり %s\n",
		Generated:      "  ✅ 生成 %s\n",
		Unchanged:      "  = 変更なし %s\n",
		ArchivedEntity: "     ⚠️  生成物でない実体を退避: %s\n",
		ArchivedHint:   "        手で編集していた場合は差分をテンプレ側へ反映してください。\n",
		WouldArchive:   "     ⚠️  生成物でない実体があります（apply すると退避されます）\n",
		Orphan:         "  ⚠️  %s の %s が届いていません（このターゲットに %s が無いため。作れば入ります）\n",
		LinkPlanned:    "  ~ リンク予定 %s -> %s\n",
		Linked:         "  🔗 リンク %s -> %s\n",
		UnlinkPlanned:  "  ~ リンク解除予定 %s\n",
		Unlinked:       "  ✂️  リンク解除 %s\n",
		LinkArchived:   "     ⚠️  リンク先に実体があったため退避: %s\n",
		LinkConflict:   "     ⚠️  名前衝突: %s\n",
		LinkKept:       "     = リンク済み %s\n",
		NoBundles:      "（バンドルがありません）",
		ColTarget:      "ターゲット",
		ColBundle:      "バンドル",
		ColContents:    "内容",
		ColDesc:        "説明",
	},
	ConfEdit: ConfEditMsg{
		LineVanished: "%s: 書き換える行が見つかりません（読み込んだ後に conf が変わった可能性があります）",
	},
	Interactive: InteractiveMsg{
		NoConfHere:       "%s に %s がありません。\n",
		SubTargetsWarn:   "⚠️  配下に既にターゲットが %d 件あります。ここに作るとこの階層自体もターゲットになります。\n",
		CreateConfirm:    "%s を作成して続けますか？",
		CreateDeclined:   "中止しました（%s は作成していません）。\n",
		SelectTitle:      "有効にするフラグ（space 切替 / enter 確定 / esc 中止）",
		DefaultOnNote:    "[既定 ON]",
		Changes:          "\n変更内容:\n",
		ChangeReplace:    "  ~ %s: %s → %s\n",
		ChangeAppend:     "  + %s = %s（追記）\n",
		NoChanges:        "\nフラグの変更はありません（%s は書き換えません）。\n",
		NoChangesNew:     "\nフラグの変更はありません（既定値のまま %s を作成します）。\n",
		ConfirmTitle:     "%s を更新して apply を実行しますか？",
		Affirmative:      "はい",
		Negative:         "いいえ",
		WroteConf:        "  ✏️  更新 %s\n",
		CreatedConf:      "  ✏️  作成 %s\n",
		Canceled:         "キャンセルしました（何も変更していません）。",
		OtherTargetsHint: "\n他に %d 件のターゲットがあります。まとめて更新するには llmtpl apply を実行してください。\n",
	},
}
