package msg

// ja は日本語のカタログ。ロケールが ja で始まるときに選ばれる。
var ja = Catalog{
	State: StateMsg{
		CannotRead:  "%s を読めません: %w",
		Corrupt:     "%s が壊れています（削除すれば次回 apply で作り直します）: %w",
		NewerFormat: "%s は新しい形式です（version %d > %d）。llmtpl を更新してください",
	},
	JSON: JSONMsg{
		NotJSON:       "%s: JSON として読めません: %w",
		NotObject:     "%s: トップレベルはオブジェクト（{...}）である必要があります",
		FormatFailed:  "JSON の整形に失敗: %w",
		TypeMismatch:  "%s: キー %q の型が一致しません（既存: %s / 断片: %s）",
		CannotCompare: "配列要素を比較できません: %w",
		TypeObject:    "オブジェクト",
		TypeArray:     "配列",
		TypeScalar:    "値",
	},
	Render: RenderMsg{
		NoTmplPath:          "TmplPath が未指定です",
		EmptySlotName:       "slot 名が空です",
		PartialsGlobFailed:  "partials の探索に失敗: %w",
		PartialsParseFailed: "partials のパースに失敗: %w",
		SourceParseFailed:   "%s のパースに失敗: %w",
		TemplateParseFailed: "テンプレートのパースに失敗: %w",
		ExecFailed:          "テンプレートの評価に失敗（未定義フラグ参照の可能性）: %w",
	},
	FileOut: FileOutMsg{
		ArchiveFailed:          "退避に失敗: %w",
		MkdirParentFailed:      "%s: 親ディレクトリを作れません: %w",
		TempCreateFailed:       "%s: 一時ファイルを作れません: %w",
		TempWriteFailed:        "%s: 一時ファイルを書けません: %w",
		TempCloseFailed:        "%s: 一時ファイルを閉じられません: %w",
		ChmodFailed:            "%s: 権限を設定できません: %w",
		ReplaceFailed:          "%s: 置き換えに失敗: %w",
		NoArchiveDir:           "%s: 生成物でない実体があるのに退避先（ArchiveDir）が未設定です",
		ArchiveDirCreateFailed: "退避先を作れません: %w",
		ArchiveNamesExhausted:  "退避先の名前が埋まっています: %s/%s",
	},
	Link: LinkMsg{
		CannotUnlink:       "%s を外せません: %w",
		WouldArchive:       "(dry-run) 退避が必要",
		CannotLink:         "%s を張れません: %w",
		CannotArchive:      "%s を退避できません: %w",
		CannotRead:         "%s を読めません: %w",
		ConflictNote:       "%s の %s は %s が先に提供しているためスキップ",
		LayerOutsideOutDir: "走査層が outDir の外を指しています: %s",
	},
	Flags: FlagsMsg{
		Section:           "%s:%d: セクションは書けません（conf は平坦な `key = value` のみ。フラグの上書きはターゲットごとの conf に書く）: %s",
		NoEquals:          "%s:%d: = がありません: %s",
		EmptyKey:          "%s:%d: キー名が空です: %s",
		BoolOnly:          "%s:%d: 値は true / false のみ: %s = %s",
		ReadFailed:        "%s: 読み込みに失敗: %w",
		EmptyValue:        "%s:%d: %s の値が空です（バンドルルートのパスを書きます）",
		PathKeyNotBool:    "%s:%d: %s はパスを書くキーです（true / false ではありません）: %s = %s",
		TildeExpandFailed: "%s:%d: %s の ~ を展開できません: %w",
		TildeUserForm:     "%s:%d: %s の ~ユーザー名 形式は使えません（絶対パスか、この conf からの相対パスで書きます）: %s",
		NoBundles:         "（バンドルがありません）",
		UnknownFlag:       "%s: 未知のフラグ: %s（同名のバンドルディレクトリがありません）。利用可能: %s",
	},
	Bundle: BundleMsg{
		CannotRead:      "%s を読めません: %w",
		CannotReadRoot:  "バンドルルートを読めません: %w",
		LayoutViolation: "バンドル %s: %s/ はバンドル直下に置けません（%s/%s/ のようにドット始まりの層へ移してください）",
		UnknownMetaKey:  "%s: %d 行目: 未知のキー: %s（使えるのは description）",
		NoColon:         "%d 行目: : がありません: %s",
		EmptyKey:        "%d 行目: キー名が空です: %s",
	},
}
